version: "3.9"

services:
  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres16
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 5
      start_period: 1s
      timeout: 10s

  service:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: python /app/src/runner.py run --symbols EURUSD,USDJPY,GBPUSD,AUDUSD,USDCAD
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres